### ISSUE TITLE
Observations about freeCAD-cheat-sheets-workbenches.pdf

### ISSUE THREAD

**Issue by luzpaz** [EvokeMadness/FreeCAD-Cheat-Sheets#2]
![image](https://user-images.githubusercontent.com/4140247/154763938-96e44e4b-bc49-496c-ba39-79141bcbcc14.png)

Also:
* Drawing workbench is deprecated in favor of TechDraw 
* Glider workbench is only available in the AppImage. So it's not worth mentioning.
* Robot workbench is unmaintained.
* Raytracing is deprecated in favor of an external workbench called [Render WB](https://github.com/FreeCAD/FreeCAD-render/)  
* Assembly workbench has been deprecated. There are 3 replacements for it that are external. They are: A2+ ([Assembly2plus](https://github.com/kbwbe/A2plus)), A3 ([Assembly3](https://github.com/realthunder/FreeCAD_assembly3)), A4 or [Assembly4](https://github.com/Zolko-123/FreeCAD_Assembly4). Each of these are separate solutions but at some point in the future they will be consolidated (see this [thread](https://forum.freecadweb.org/viewtopic.php?f=20&t=34583) for more details.)

**Comment by EvokeMadness** [comment]
Hi,

Thanks for the feedback and input! This insight is valuable to the project because I don't use FreeCAD daily. I am not too involved with the community and the development around FreeCAD. Do you think it would be beneficial to add a short description of the workbench's utility?

**Comment by luzpaz** [comment]
Yes, I think adding a short description would be awesome. I also think that from a philosophical/pragmatic it's worth emphasizing the 20/80 rule which is 80% of the most widely used outcome using FreeCAD happens in 20% of the tools. That is usually PartDesign, Sketcher, and occasionally TechDraw. So perhaps curating the information with that in mind can help navigate the overwhelm of tools available in the FreeCAD UI. 

An aside, one could make an argument that Part workbench is also useful but it's considered the old-school method. 

Essentially, there is the Part WB (this came before PartDesign) and it uses the [CSG](https://wiki.freecad.org/Constructive_solid_geometry ) modeling methodology. Later, the PartDesign workbench introduced a more modern approach called [Feature editing](https://wiki.freecadweb.org/Feature_editing). Unfortunately, they weren't named strategically (too similar) and they get mixed up. They aren't compatible unless you know what you're doing.

**Comment by EvokeMadness** [comment]
Definitely agree with the 20/80 thing. While Part WB is not part of every workflow, it's still important when editing solid geometry and creating complex geometry. But only after it's been created in Part Design or another program. I too wish it was renamed to something more intuitive, reducing confusion and limiting redundancy. Hopefully, a description on Part WB and Part Design will clear up some confusion.
